BIN:
  NUM_REG_BIN: 10
  USE_DIS_BIN: True
#  BIN_LAMBDA: 0.1
  BIN_LAMBDA: 0.5

MODEL:
  META_ARCHITECTURE: "GeneralizedRCNN"
#  WEIGHT: './S0/model_rs.pth' # Initialed by pretrained weight
  WEIGHT: '/data/piaozhengquan/projects/DAOD/MGADA-master/FCOS/debug/models_pp_LRA_so_bin_sup_s1_adv/bin_sup_only_da_ga_cityscapes_VGG_16_FPN_4x/model_last.pth'
#  WEIGHT: '/data/piaozhengquan/projects/DAOD/MGADA-master/FCOS/debug/S1_da_ga_cityscapes_VGG_16_FPN_4x/model_0017500.pth'

  #
  RPN_ONLY: True
  FCOS_ON: True
  DA_ON: True
  BACKBONE:
    CONV_BODY: "VGG-16-FPN-RETINANET"
  RETINANET:
    USE_C5: False # FCOS uses P5 instead of C5
  GENBOX:
      FPN_STRIDES: [8, 16, 32, 64, 128]
      NUM: 5
      NUM_CONVS: 4
  GENFEATURE:
      LOCAL_GLOBAL_MERGE: True
      TWOMULTSCALE: True
      FPN_STRIDES: [8, 16, 32, 64, 128]
      POOLER_SCALES: [0.125, 0.0625, 0.03125, 0.015625, 0.0078125]
      POOLER_RESOLUTION: 7
      POOLER_SAMPLING_RATIO: 0
  FCOS:
    NUM_CLASSES: 9
    INFERENCE_TH: 0.05    # pre_nms_thresh    (default=0.05)
    PRE_NMS_TOP_N: 1000   # pre_nms_top_n     (default=1000)
    NMS_TH: 0.5           # nms_thresh        (default=0.6)
    NUM_CONVS: 4
  INS:
      #
      USE_DIS_GLOBAL: True
      #
      DT_DIS_LAMBDA: 0.1
      GRL_APPLIED_DOMAIN: 'both'
      #
      USE_DIS_P7: True
      USE_DIS_P6: True
      USE_DIS_P5: True
      USE_DIS_P4: True
      USE_DIS_P3: True
      #
      DIS_P7_NUM_CONVS: 4
      DIS_P6_NUM_CONVS: 4
      DIS_P5_NUM_CONVS: 4
      DIS_P4_NUM_CONVS: 4
      DIS_P3_NUM_CONVS: 4
      #
      GRL_WEIGHT_P7: 0.01
      GRL_WEIGHT_P6: 0.01
      GRL_WEIGHT_P5: 0.01
      GRL_WEIGHT_P4: 0.01
      GRL_WEIGHT_P3: 0.01
  ADV:
    #
    USE_DIS_GLOBAL: True
    USE_DIS_CENTER_AWARE: False
    #
    GA_DIS_LAMBDA: 0.1
    GRL_APPLIED_DOMAIN: 'both'
    #
    USE_DIS_P7: True
    USE_DIS_P6: True
    USE_DIS_P5: True
    USE_DIS_P4: True
    USE_DIS_P3: True
    #
    DIS_P7_NUM_CONVS: 4
    DIS_P6_NUM_CONVS: 4
    DIS_P5_NUM_CONVS: 4
    DIS_P4_NUM_CONVS: 4
    DIS_P3_NUM_CONVS: 4
    #
    GRL_WEIGHT_P7: 0.01
    GRL_WEIGHT_P6: 0.01
    GRL_WEIGHT_P5: 0.01
    GRL_WEIGHT_P4: 0.01
    GRL_WEIGHT_P3: 0.01

  CM:
      #
      USE_CM_GLOBAL: True
      #
      GL_CM_LAMBDA: 0.2
      GRL_APPLIED_DOMAIN: 'both'
      #
      USE_DIS_P7: True
      USE_DIS_P6: True
      USE_DIS_P5: True
      USE_DIS_P4: True
      USE_DIS_P3: True
      #
      DIS_P7_NUM_CONVS: 4
      DIS_P6_NUM_CONVS: 4
      DIS_P5_NUM_CONVS: 4
      DIS_P4_NUM_CONVS: 4
      DIS_P3_NUM_CONVS: 4
      #
      GRL_WEIGHT_P7: 0.01
      GRL_WEIGHT_P6: 0.01
      GRL_WEIGHT_P5: 0.01
      GRL_WEIGHT_P4: 0.01
      GRL_WEIGHT_P3: 0.01

      LOSS_DIRECT_W: 1.0
      LOSS_GRL_W: 0.1
      SAMPLES_THRESH: 0.5

TEST:
  DETECTIONS_PER_IMG: 100 # fpn_post_nms_top_n  (default=100)
  LEVEL_NUMS: [30, 30, 30, 30, 30]
DATASETS:
  TRAIN_SOURCE: ("cityscapes_train_cocostyle", )
  TRAIN_TARGET: ("cityscapes_foggy_train_cocostyle", )
  TEST: ("cityscapes_foggy_val_cocostyle", )
INPUT:
  MIN_SIZE_RANGE_TRAIN: (640, 800)
  MAX_SIZE_TRAIN: 1333
  MIN_SIZE_TEST: 800
  MAX_SIZE_TEST: 1333
DATALOADER:
  SIZE_DIVISIBILITY: 32
  #NUM_WORKERS: 2
SOLVER:
  WEIGHT_DECAY: 0.0001
  MAX_ITER: 29000
#  IMS_PER_BATCH: 20
  IMS_PER_BATCH: 14
#  IMS_PER_BATCH: 10
#  IMS_PER_BATCH: 2
  CHECKPOINT_PERIOD: 500
  #
  BACKBONE:
    BASE_LR: 0.005
    STEPS: (120000, 160000)
    WARMUP_ITERS: 500
    WARMUP_METHOD: "constant"
  #
  GENBOX:
    BASE_LR: 0.005
    STEPS: (120000, 160000)
    WARMUP_ITERS: 500
    WARMUP_METHOD: "constant"
  #
  GENFEATURE:
    BASE_LR: 0.005
    STEPS: (120000, 160000)
    WARMUP_ITERS: 500
    WARMUP_METHOD: "constant"
  #
  FCOS:
    BASE_LR: 0.005
    STEPS: (120000, 160000)
    WARMUP_ITERS: 500
    WARMUP_METHOD: "constant"
  #
  DIS:
    BASE_LR: 0.005
    STEPS: (120000, 160000)
    WARMUP_ITERS: 500
    WARMUP_METHOD: "constant"
