from .fcos_head_discriminator import FCOSDiscriminator
from .fcos_head_discriminator_CA import FCOSDiscriminator_CA
from .fcos_head_discriminator_CM import FCOSDiscriminator_CM
from .fcos_head_discriminator_BIN import FCOSDiscriminator_BIN