MODEL:
  BACKBONE:
    NAME: 'resnet101'
  RPN:
    ANCHOR_SIZES: (64, 128, 256, 512)
  ROI_BOX_HEAD:
    NUM_CLASSES: 7
    BOX_PREDICTOR: 'resnet101_predictor'
    POOL_TYPE: 'align'
ADV:
  LAYERS: [True, False, True]
  LAMBDA_FROM: 1.0
  LAMBDA_TO: 0.1
  DIS_MODEL:
    - in_channels: 256
      embedding_kernel_size: 1
      embedding_norm: True
      embedding_dropout: True
      func_name: 'cross_entropy'
      pool_type: 'avg'
      loss_weight: 0.01
      window_strides: [2, 2, 2, 2, 2, 2, 2]
      window_sizes: [3, 9, 15, 21, 27, 33, 38]
    - in_channels: 1024
      func_name: 'cross_entropy'
      pool_type: 'avg'
      loss_weight: 0.01
      window_strides: [2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2]
      window_sizes: [3, 6, 9, 12, 15, 18, 21, 24, 27, 30, 33, 35, 38]
DATASETS:
  TRAINS: ['watercolor_voc_2007_trainval', 'watercolor_voc_2012_trainval']
  TARGETS: ['watercolor_train']
  TESTS: ['watercolor_test']
INPUT:
  TRANSFORMS_TRAIN:
    - name: 'random_flip'
    - name: 'resize'
      min_size: 600
    - name: 'normalize'
      mean: [0.5, 0.5, 0.5]
      std: [0.5, 0.5, 0.5]
      to_01: True
    - name: 'collect'
  TRANSFORMS_TEST:
    - name: 'resize'
      min_size: 600
    - name: 'normalize'
      mean: [0.5, 0.5, 0.5]
      std: [0.5, 0.5, 0.5]
      to_01: True
    - name: 'collect'
SOLVER:
  EPOCHS: 10
  STEPS: (8, 9)
  LR: 1e-5
  BATCH_SIZE: 1
TEST:
  EVAL_TYPES: ['voc']

WORK_DIR: './debug/adv_voc_2_watercolor'