MODEL:
  MASK_ON: True
  BACKBONE:
    NAME: 'resnet101'
  RPN:
    POST_NMS_TOP_N_TEST: 500
    ANCHOR_SIZES: (32, 64, 128, 256, 512)
  ROI_HEADS:
    BATCH_SIZE_PER_IMAGE: 256
  ROI_BOX_HEAD:
    NUM_CLASSES: 2
    BOX_PREDICTOR: 'resnet101_predictor'
    POOL_TYPE: 'align'
ADV:
  LAYERS: [False, False, True]
  LAMBDA_FROM: 1.0
  LAMBDA_TO: 1.0
  DIS_MODEL:
    - in_channels: 1024
      func_name: 'cross_entropy'
      pool_type: 'avg'
      loss_weight: 0.1
      window_strides: [2, 2, 2, 2, 2, 2, 2]
      window_sizes: [3, 9, 15, 21, 27, 33, 37]
DATASETS:
  TRAINS: ['vkitti']
  TARGETS: ['cityscapes_train']
  TESTS: ['car_city_val']
INPUT:
  TRANSFORMS_TRAIN:
    - name: 'random_flip'
    - name: 'resize'
      min_size: 600
    - name: 'normalize'
      mean: [0.5, 0.5, 0.5]
      std: [0.5, 0.5, 0.5]
      to_01: True
    - name: 'collect'
  TRANSFORMS_TEST:
    - name: 'resize'
      min_size: 600
    - name: 'normalize'
      mean: [0.5, 0.5, 0.5]
      std: [0.5, 0.5, 0.5]
      to_01: True
    - name: 'collect'
SOLVER:
  EPOCHS: 18
  STEPS: (12, 16)
  LR: 1e-5
  BATCH_SIZE: 1
TEST:
  EVAL_TYPES: ['coco']

WORK_DIR: './debug/adv_vkitti_2_cityscapes_mask'