ADV:
  DIS_MODEL: [{'in_channels': 512}]
  FOCAL_LOSS_GAMMA: 5
  LAMBDA_FROM: 1.0
  LAMBDA_TO: 1.0
  LAYERS: [False, False, True]
  LOSS_FUNC: focal_loss
  LOSS_WEIGHT: 1.0
DATALOADER:
  NUM_WORKERS: 8
DATASETS:
  TARGETS: ()
  TESTS: ()
  TRAINS: ()
INPUT:
  TRANSFORMS_TEST: []
  TRANSFORMS_TRAIN: []
MODEL:
  BACKBONE:
    NAME: vgg16
  GENFEATURE:
    FPN_STRIDES: [0.0625]
    LOCAL_GLOBAL_MERGE: True
    TWOMULTSCALE: True
  MASK_ON: False
  ROI_BOX_HEAD:
    BOX_PREDICTOR: vgg16_predictor
    NUM_CLASSES: 9
    POOL_RESOLUTION: 7
    POOL_SPATIAL_SCALE: 0.0625
    POOL_TYPE: pooling
  ROI_HEADS:
    BATCH_SIZE_PER_IMAGE: 128
    DETECTIONS_PER_IMG: 100
    NMS_THRESH_TEST: 0.5
    SCORE_THRESH_TEST: 0.0
  ROI_ONE_DIS:
    CLS:
      DISCRIMINATOR: OneFCOSDiscriminator_cc
      GRL_LAMBDA: 0.01
      LOSS_DIRECT_W: 1.0
      LOSS_GRL_W: 1.0
      LOSS_WEIGHT: 1.0
      MON: False
      NUM_CLASSES: 1
      NUM_CONVS: 4
      SAMPLES_THRESH: 0.5
    DOM:
      DISCRIMINATOR: OneFCOSDiscriminator
      GRL_LAMBDA: 0.01
      LOSS_WEIGHT: 1.0
      MON: False
      NUM_CONVS: 4
  ROI_TWO_DIS:
    CLS:
      DISCRIMINATOR: VGG16TwoDiscriminator_cc
      GRL_LAMBDA: 0.01
      LOSS_DIRECT_W: 1.0
      LOSS_GRL_W: 1.0
      LOSS_WEIGHT: 1.0
      MON: False
      NUM_CLASSES: 1
      POOL_RESOLUTION: 7
      SAMPLES_THRESH: 0.5
    DOM:
      DISCRIMINATOR: VGG16TwoDiscriminator
      GRL_LAMBDA: 0.01
      LOSS_WEIGHT: 1.0
      MON: False
      POOL_RESOLUTION: 7
  RPN:
    ANCHOR_SIZES: (128, 256, 512)
    ANCHOR_STRIDE: 16
    ASPECT_RATIOS: (0.5, 1, 2)
    BATCH_SIZE_PER_IMAGE: 256
    MIN_SIZE: 1
    NMS_THRESH: 0.7
    NUM_CHANNELS: 512
    POST_NMS_TOP_N_TEST: 300
    POST_NMS_TOP_N_TRAIN: 2000
    PRE_NMS_TOP_N_TEST: 6000
    PRE_NMS_TOP_N_TRAIN: 12000
SOLVER:
  BATCH_SIZE: 1
  EPOCHS: 25
  GAMMA: 0.1
  LR: 5e-06
  MOMENTUM: 0.9
  STEPS: (16, 22)
  WEIGHT_DECAY: 0.0001
TEST:
  EVAL_TYPES: ('voc',)
WORK_DIR: ./work_dir